name: CI Pipeline

# Trigger the workflow on pushes and pull requests to the main branch.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment (adjust if using another language)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests (or any other commands, e.g., build, lint, etc.)
      - name: Run tests
        run: npm test
